# Generated by Django 5.1.3 on 2024-11-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
