# Generated by Django 5.1.3 on 2024-11-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('quality', models.IntegerField(default='10')),
                ('seller', models.CharField(max_length=200, unique=True)),
                ('location', models.JSONField(default={'lat': 0, 'lon': 0})),
            ],
        ),
    ]
