# Generated by Django 5.1.3 on 2024-11-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_product_status_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='ProductId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
    ]
