# Generated by Django 5.1.3 on 2024-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200, unique=True)),
                ('experience', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned')], default='assigned', max_length=20)),
            ],
        ),
    ]
