# Generated by Django 5.1.3 on 2024-11-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('condition', models.IntegerField(default=0)),
                ('topbid', models.IntegerField()),
            ],
        ),
    ]
