# Generated by Django 5.1.3 on 2024-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('quality', models.IntegerField(default=10)),
                ('seller_id', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
    ]
